services:
  - type: web
    name: tarot-webapp
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: X-Frame-Options
        value: "ALLOWALL"
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *"
